apiVersion: apps/v1
kind: Deployment
metadata:
  name: scientific-scrapper
  namespace: scientific
spec:
  selector:
    matchLabels:
      app: scientific-scrapper
  template:
    metadata:
      labels:
        app: scientific-scrapper
    spec:
      containers:
        - name: scientific-scrapper
          image: ghcr.io/harpiechoise/scientific-scrapper:latest
          resources:
            limits:
              memory: "256Mi"
              cpu: "200m"
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: secret-scientific
            - configMapRef:
                name: scientific-configmap
